### PR TITLE
Update database

### PR DESCRIPTION
**Pull request by ess2024**
the whole tables in database are done
if anyone have a comment please provide here

### CODE REVIEW

**Comment by 1nourhan** [comment]
I have modified Acception class and there is no need for the acception list table, please drop that table.

**Comment by Sallykamel** [comment]
i have made a modification and we won't need the tables of donation in the database

**Comment by ess2024** [comment]
i will review it and modify it

**Comment by ess2024** [comment]
i have updated what u mentioned about database

**Comment by SalmaSaeed29** [comment]
added tables are all set

**Pull request merged**
