### PR TITLE
acception database queries to get authorities

### PR DESCRIPTION
**Pull request by 1nourhan**
database queries to get hospitals which have compatible available blood bags

### CODE REVIEW

**Comment by ess2024** [comment]
please edit ur acception class to return region and city with address for hospitals that are far from the acceptor

**Comment by 1nourhan** [comment]
> please edit ur acception class to return region and city with address for hospitals that are far from the acceptor

i will modify it

**Comment by 1nourhan** [comment]
i modify it.

**Comment by ess2024** [comment]
great job nourhan

**Pull request merged**
